# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.__config__.show)

1.20.1
<function show at 0x00000131C77695E0>


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
zero_array = np.zeros(10,)
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
print(zero_array.nbytes)
print(zero_array.size * zero_array.itemsize)
print(np.prod(zero_array.shape) * zero_array.itemsize)

80
80
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
 n1 = np.arange(10, 50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
n1[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
mat = np.array([1,2,0,0,4,0])
np.where(mat != 0)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
mat1 = np.identity(3)
mat2 = np.eye(3)
print(mat1)
print(mat2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
mat = np.random.random((3, 3, 3))
print(mat)

[[[0.06878839 0.50795932 0.65739882]
  [0.38385085 0.52639638 0.81085748]
  [0.9154285  0.897796   0.84664244]]

 [[0.03704634 0.49569864 0.95131759]
  [0.86668573 0.50657932 0.27628211]
  [0.81957747 0.28476017 0.83854495]]

 [[0.76695031 0.30782344 0.98944113]
  [0.1728267  0.83765918 0.61641109]
  [0.74689543 0.11714637 0.84173769]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
mat = np.random.random((10, 10))
print('minimum value: {}'.format(np.round(mat.min(), 4)))
print('maximum value: {}'.format(np.round(mat.max(), 4)))

minimum value: 0.0143
maximum value: 0.9967


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
vec = np.random.random(30)
print(vec)
print(vec.mean())

[0.06590234 0.15789977 0.28852637 0.94722466 0.1991263  0.86646563
 0.19813712 0.29301504 0.82477485 0.1728678  0.54232577 0.81023424
 0.45680247 0.05119563 0.71333211 0.20352872 0.36672696 0.44823197
 0.26243438 0.04112047 0.01105297 0.96506748 0.71275362 0.45220852
 0.71673658 0.61891146 0.98475664 0.79775841 0.07430136 0.39959863]
0.454767275136594


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
mat = np.ones((5, 5))
print(mat)

mat[1:-1, 1:-1] = 0
print(mat)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
mat = np.ones((3, 3))
print(mat)

mat = np.pad(mat, pad_width=1, mode='constant', constant_values=0)
print(mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
mat = np.diag([1, 2, 3, 4], k=-1)
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [3]:
x = np.random.random((5,5))
normalize = (x - np.mean(x)) / np.std(x)
normalize

array([[-0.48657845,  0.66835402, -0.01131211,  1.17267123,  0.53925417],
       [-1.6563511 ,  0.48989099,  1.20213461, -1.83850267, -0.95883879],
       [ 0.93852975, -1.25993585,  0.13377436,  0.25296074, -0.71754392],
       [ 1.47320696,  0.9684598 ,  1.39105142, -0.70640664,  0.01864922],
       [ 1.22241825, -0.05629991, -1.79055925, -0.24748253, -0.74154428]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [4]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

<ipython-input-4-4daa7c2f2b60>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [5]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [10]:
Z = np.arange(11)
print(Z)
print(Z**Z) 
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z) # illegal

[ 0  1  2  3  4  5  6  7  8  9 10]
[         1          1          4         27        256       3125
      46656     823543   16777216  387420489 1410065408]
[  0   1   2   4   8  16  32  64 128 256 512]
[False False False False False False False False False False False]
[0. +0.j 0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j
 0. +9.j 0.+10.j]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [42]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0)) 
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-42-ef88ca4f69d5>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-42-ef88ca4f69d5>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [14]:
Z = np.random.uniform(-10,10,10)
np.copysign(np.ceil(np.abs(Z)),Z)

array([ 2., -4.,  2.,  3., -6., -9.,  7.,  3.,  3.,  5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [15]:
A = np.random.randint(0,10,10)
B = np.random.randint(0,10,10)
print(A,B)
np.intersect1d(A,B)

[6 1 8 3 3 9 3 9 1 7] [4 3 5 4 8 8 9 8 1 8]


array([1, 3, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [18]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [43]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


<ipython-input-43-c6ff0ad7fd7b>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [4]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [3]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [5]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out = B)
np.divide(A,2,out = A)
np.negative(A,out = A)
np.multiply(A,B,out = A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [6]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[0. 5. 4. 1. 2. 4. 0. 1. 9. 4.]
[0. 5. 4. 1. 2. 4. 0. 1. 9. 4.]
[0. 5. 4. 1. 2. 4. 0. 1. 9. 4.]
[0 5 4 1 2 4 0 1 9 4]
[0. 5. 4. 1. 2. 4. 0. 1. 9. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [7]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [8]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [9]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [10]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.14175496 0.25820282 0.35459617 0.40317028 0.43127155 0.6089118
 0.61444161 0.65077183 0.89638661 0.94833535]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [30]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [12]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [13]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [14]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.53436045 0.32192469 0.54931256 0.54681784 1.13439733 1.25101946
 0.20559497 0.84979757 0.90902568 0.90723697]
[0.82241878 1.54622401 0.00748816 0.0115134  0.73726788 0.7069196
 1.55853634 1.25690722 0.97920936 1.1539288 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [15]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.87516748 0.15575964 0.91330424 0.01851794 0.35398379 0.51387694
 0.07691346 0.         0.28987839 0.23608155]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [16]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [31]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [18]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [19]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [20]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

37


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [21]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-21-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [32]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.34643216 0.32360184 0.28623272 0.26818569 0.03958443
  0.51938607 0.06348265 0.54714092 0.54327437]
 [0.34643216 0.         0.23398398 0.46460641 0.60510527 0.36671975
  0.51350487 0.30576537 0.36482253 0.37948731]
 [0.32360184 0.23398398 0.         0.56303079 0.58256742 0.36078221
  0.70034887 0.32616664 0.22354724 0.60569928]
 [0.28623272 0.46460641 0.56303079 0.         0.3008056  0.25059996
  0.2849649  0.24829727 0.77634049 0.42143846]
 [0.26818569 0.60510527 0.58256742 0.3008056  0.         0.2400204
  0.58518765 0.2993472  0.80373151 0.70254568]
 [0.03958443 0.36671975 0.36078221 0.25059996 0.2400204  0.
  0.49408522 0.06362883 0.58427279 0.53381835]
 [0.51938607 0.51350487 0.70034887 0.2849649  0.58518765 0.49408522
  0.         0.46185611 0.8761788  0.23633656]
 [0.06348265 0.30576537 0.32616664 0.24829727 0.2993472  0.06362883
  0.46185611 0.         0.54745942 0.47983937]
 [0.54714092 0.36482253 0.22354724 0.77634049 0.80373151 0.58427279
  0.8761788  0.547459

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [24]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[61 50 23 13 31 80 86 12 83  4]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [25]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-25-dc1069bf6c21>:10: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [26]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [27]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [33]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [47]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.12137372 -0.12656955 -0.11454859 -0.17871219  0.04668923 -0.21246327
   0.02447794  0.11058556  0.31879156  0.25312304]
 [ 0.07035184  0.18761182 -0.4745063   0.0414105   0.14386286 -0.50203286
   0.35463451  0.14152607 -0.06951546  0.10665704]
 [ 0.40098383  0.03232197 -0.2868455  -0.18740393  0.39293562  0.18846941
  -0.04078384 -0.51977223 -0.05790691  0.07800158]
 [ 0.23085074 -0.2573813   0.18463405  0.30331236  0.01770664 -0.26951884
  -0.30646217 -0.04229305 -0.08227069  0.22142226]
 [-0.2173303   0.2924576   0.02127125  0.33639403 -0.43722221  0.17354539
  -0.24025613  0.19289286 -0.16137123  0.03961874]]


#### 59. How to sort an array by the nth column? (★★☆)

In [35]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[5 0 8]
 [4 1 0]
 [1 7 3]]
[[5 0 8]
 [4 1 0]
 [1 7 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [46]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [37]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5419129995561703


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [38]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [39]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [41]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
np.add.at(Z, I, 1)
print(Z)

[3. 2. 4. 3. 4. 2. 3. 2. 2. 5.]
[5. 3. 7. 5. 7. 3. 5. 3. 3. 9.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [42]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [45]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)